@RD /S /Q "G:\gamedev\mmo-client\Library"
@RD /S /Q "G:\gamedev\mmo-client\Logs"
@RD /S /Q "G:\gamedev\mmo-client\obj"
@RD /S /Q "G:\gamedev\mmo-client\Packages"
@RD /S /Q "G:\gamedev\mmo-client\Temp"